# Generated by Django 5.2.4 on 2025-09-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='coach/images/')),
                ('program', models.CharField(max_length=400)),
                ('courses', models.CharField(max_length=400)),
            ],
        ),
    ]
