# Generated by Django 5.2.7 on 2025-12-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='ProgramCategory',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='url',
        ),
    ]
