# Generated by Django 5.2.7 on 2025-12-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_programs_programcategory_remove_exercise_url'),
    ]

    operations = [
    ]
