# Generated by Django 5.2.7 on 2025-12-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20251204_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramCategory',
            new_name='Programs',
        ),
    ]
