# Generated by Django 5.2.7 on 2026-01-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='program_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
            },
        ),
        migrations.CreateModel(
            name='CoachCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Программа')),
                ('description', models.TextField(blank=True, verbose_name='Описание программы')),
            ],
        ),
    ]
