# Generated by Django 5.2.4 on 2025-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='program',
        ),
        migrations.AddField(
            model_name='coach',
            name='demo_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='coach',
            name='source_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='coach',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
