# Generated by Django 5.2.7 on 2026-01-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_remove_coach_courses_remove_coach_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
