# Generated by Django 5.2.7 on 2026-01-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favouriteexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteExercise',
        ),
    ]
